# docker-compose.yml
version: '3.8'
services:
  validator-keys-tool:
    build:
      context: ./docker/validator-keys-tool
    image: local-validator-keys-tool:latest
    container_name: validator-keys-tool
    platform: linux/amd64
    restart: unless-stopped

  validator1:
    build:
      context: ./docker/validator
      args:
        VALIDATOR_NAME: validator1
    container_name: validator1
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./docker/validator/shared/validators.txt
        target: /etc/opt/ripple/validators.txt
    depends_on:
      - validator-keys-tool
    restart: unless-stopped
    ports:
      - "51235:51235"
      - "6006:6006"

  validator2:
    build:
      context: ./docker/validator
      args:
        VALIDATOR_NAME: validator2
    container_name: validator2
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./docker/validator/shared/validators.txt
        target: /etc/opt/ripple/validators.txt
    depends_on:
      - validator-keys-tool
    restart: unless-stopped