version: '3.8'
services:
  validator1:
    build:
      context: ./docker/validator1
    container_name: validator1
    platform: linux/amd64
    ports:
      - "8080:80"
      - "5005:5005"
    volumes:
      - ./docker/validator1/config:/config
    restart: unless-stopped